# Generated by Django 5.0.6 on 2024-06-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
